---
- name: Converge
  hosts: all
  tasks:
    - name: "Include role"
      include_role:
          name: "socks5-reverse-proxy"
      vars:
          systemd_enable: false
          socks_port: 9050
          socks_host: 127.0.0.1
          ports:
              - name: http-passthrough
                local_port: 8101
                bind_ip: 127.0.0.1
                remote_port: 443
                remote_host: duckduckgo.com
                systemd_enabled: true
                systemd_restart: false
                type: "tls"  # forward as tcp on tls port only for testing
