---
dependency:
    name: galaxy
driver:
    name: docker
platforms:
    - name: ubuntu-20.04-systemd
      image: jrei/systemd-ubuntu
      pre_build_image: true
provisioner:
    name: ansible
    playbooks:
        prepare: prepare.yml
verifier:
    name: ansible
