---
dependency:
    name: galaxy
driver:
    name: docker
platforms:
    - name: instance
      image: python:3.10-bullseye
      pre_build_image: true
provisioner:
    name: ansible
    playbooks:
        prepare: prepare.yml
verifier:
    name: ansible
